---
- name: Deploy MERN Application
  hosts: webservers
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install Node.js and npm
      apt:
        name: [nodejs, npm]
        state: present
    - name: Clone Application Repository
      git:
        repo: 'https://github.com/UnpredictablePrashant/TravelMemory'
        dest: /home/ubuntu/TravelMemory
    - name: Install backend dependencies
      shell: npm install
      args:
        chdir: /home/ubuntu/TravelMemory/backend
    - name: Install frontend dependencies
      shell: npm install
      args:
        chdir: /home/ubuntu/TravelMemory/frontend
